apiVersion: v1
kind: Service
metadata:
  name: flask-apis-service
spec:
  selector:
    app: flask-apis
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 9090
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-apis
spec:
  selector:
    matchLabels:
      app: flask-apis
  replicas: 4
  template:
    metadata:
      labels:
        app: flask-apis
    spec:
      containers:
      - name: flask-apis
        image: flask-apis:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9090